version: '3.1'
services:
  frontend-app:
    build:
      context: ./frontend
    ports: 
      - '80:80'
    volumes:
      - './frontend/html:/usr/share/nginx/html'
    restart: always

  backend-api:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - './backend:/opt/app'
    restart: always